### ISSUE TITLE
Add command to update contract to the head of the template

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#17]
Suggested by @andynog during usage 

> As an enhacement the neat-contract tool could have an option something like neat-contract compile --update-template that would force it to update to the latest on master

(https://informalsystems.slack.com/archives/CRX6MTEFL/p1587156595128300?thread_ts=1586456804.054300&cid=CRX6MTEFL)

**Comment by thanethomson** [comment]
This is now taken care of in v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`).

See `themis-contract update -h` for details.
