### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#2]
(Notes from video sync with @thanethomson.)

For internal (and eventually external users) we'll want some packaging that can handle the system dependencies. We might start with a bash script (as discussed) but we could also consider using using system package managers (e.g.g, homebrew, apt).

We could also consider making a nix package, which should provide flexible cross-platform package management. I'd be willing to explore packing it via nix if we agreed this would be worth exploring.

In any case, we'll probably want to help users configure their node packages to install locally to a user, so as not to need root access. See https://github.com/glenpike/npm-g_nosudo for a script that does this.

**Comment by zramsay** [comment]
brew
