### ISSUE TITLE
Add command to update template hash

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/themis-contract#22]
We should have some kind of sub-command to help automatically update the hash of a template in a contract to the latest hash. It's a pain to have to manually run `sha256sum contract-template.md` and copy/paste the hash every time one updates a template.

**Comment by shonfeder** [comment]
Would this be included as part of  #17 ?

**Comment by thanethomson** [comment]
Actually yes, this is a duplicate issue then. Closing in favour of #17 👍
