### ISSUE TITLE
Work out best-practices/tooling for negotiating and drafting

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#23]
Contract templates to be revised, whether because of negotiation or because circumstances and requirements change. With what we currently have in place, revision can effect two documents:

1. The paramters file
2. The template itself

The process for the first is easy enough: parties can make changes to the repository holding the parameters, to change the specific terms of an agreement.

But what's the process for revising templates? If changes are just internal, and due to changing business needs, they can be unilaterally changed and incorporated into the template. But for negotiation between parties, it's not so clear. Two options that occur to me:

1. Negotiation takes place on a fork, allowing private negotiation over the content to be effected through commits, conversation, and PRs. The parties responsible for drafting the template could then pull some or all of these changes into upstream fork at their discretion. 
1. Negotiation results in new parameterization of the template. In some cases, this is probably useful and advisable, but in other cases it should probably be avoided, unless the parties wants to invite negotiation over the terms in question.

**Comment by shonfeder** [comment]
I think this is something that will come into clearer focus as we use the tool more and as it takes shape.

**Comment by ebuchman** [comment]
I think we need a way to be able to make local changes to a template for a specific contract and track the commit hashes for those changes within the template file. 

The tool should have native functionality for seeing what changes were applied to an original template.

**Comment by thanethomson** [comment]
> I think we need a way to be able to make local changes to a template for a specific contract and track the commit hashes for those changes within the template file.
> 
> The tool should have native functionality for seeing what changes were applied to an original template.

Could you please sketch out a practical example of what you're talking about here? I don't totally understand. Does Git not provide enough in terms of version control?

**Comment by thanethomson** [comment]
One feature lacking from the template languages we've been using up to now (Mustache and Handlebars) has been the ability to **override** certain sections of the base template. Perhaps this could fulfill our needs?

Jinja2 and other similar template engines offer [template inheritance](https://jinja.palletsprojects.com/en/2.11.x/templates/#template-inheritance) that allows for (1) deriving one template from another (recursively), and (2) overriding named blocks within any of the parent templates.

We'd have to do some thinking/design work here to figure out how, practically, to implement this though. There may be hidden trade-offs I haven't considered yet to going down this route.

**Comment by shonfeder** [comment]
I had a few thoughts on the topic of template inheritance for this purpose, inspired by Thane's example on #25.
 
I imagine there is a set of cases where such inheritance could certainly be useful.However, I'm not sure that it will be particularly helpful for needs of ad-hoc contract negotiation, which this issue is meant to address

Also, IIUC, it's already possible to achieve the effect of overriding particular clauses mustache, without any need for an inclusion mechanism. E.g., in the contract: 

```
{{^alternative_clause}}
This is the default clause that should be used.
{{/alternative_clause}}
{{#alternative_clause}}
{{.}}
{{#alternative_clause}}
```

Then, if the `alternative_clause` is specified in the config file, it will override the default, but if it's absent, the default will be used. Jinja2's contract inheritance may winout because it's slightly more succinct, but the basic functionality of overriding clauses isn't missing in our current set up.

However, I'm still not clear on whether parameterized overrides will be sufficient to the needs of adhoc contract negotiation or whether we'll really just need the flexibility of making unparameterized changes to contracts (which we'll want that tracked in git). Potentially, *any clause* could be negotiated, so do we wrap every single clause as a block like this just to preempt potential overrides later? (This effectively flags to the reader that every clause is negotiable, btw, something which I think might have unwelcome consequences.)

Or do we just wait until a party wants to negotiate the terms of some usually standard clause, and then wrap the blocks to make them overridable? In that case, where do we make this change? Do we push the change all the way upstream, so that our main template now has this overridable block going forward? This may not be helpful if some party wants a very specific change to a clause that usually isn't negotiated. Instead we could just add the override block to the local template copy (which we know now we'll need). But now we actually have the same problem we began with, which is that we've had to make a change to the text of the template locally, and that'll need to be tracked!

**Comment by thanethomson** [comment]
So if you've got a template and you want the entire template's contents overrided, technically you're just creating a totally new template, right? So each template's going to have to have some level of structure that's fixed and that won't change over time for it to be considered a template at all.

The level to which we can override the contents of a template is totally up to us as we build the template. Nothing stops us from defining a template like so:

```markdown
# Agreement

{% block basic_terms %}
## Basic Terms

1. Terms
2. Go
3. Here
{% endblock %}

{% block limitation_of_liability %}
## Limitation of Liability

More conditions go here.
{% endblock %}
```

The level of granularity we choose here is totally up to us. You could even go more fine-grained and [nest blocks within other blocks](https://jinja.palletsprojects.com/en/2.11.x/templates/#block-nesting-and-scope), only overriding the nested block without modifying its outer block's contents.

The Jinja2-style approach does away with the need for management of an external context variable for each separate clause, resulting in a simpler interface.

**Tracking changes** using Jinja2-style templates is trivial, because it's self-evident which blocks have been overridden. Even if we continue with the approach of separation of parameters and template files, a local template will only capture the very specific changes that've been made to the upstream template.

**Comment by thanethomson** [comment]
I think we now have a reasonable approach to dealing with this in v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`).

We consider a contract to be defined by way of 3 files:

1. A `contract.dhall` file (the entrypoint for the contract). This keeps track of which contract it was derived from (its "upstream" contract), as well as details of the other 2 files below.
2. A `params.dhall` file (or `params.{toml|json|yaml}`), in which you can define and negotiate contract parameters with the counterparties.
3. A `template.md` file (or `template.tex`), which is initially a precise copy of the upstream contract's template file, and which you can use to negotiate the content of your template. Some rudimentary mechanisms are provided by Themis Contract to see the differences between the original template and your local template.

In future, we'll most likely have to add support for additional supporting files, but we'll consider this in a separate issue.
