### ISSUE TITLE
The `globby` dependency is not being installed using the documented installation command

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#3]
The readme current instructs users to run `npm i -g` to install the package globally. On my system, this resulted in a broken installation, since the `globby` package was not installed but it is a transitive runtime dependency.

I suspect this is because it is only listed as a `devDependencies` https://github.com/informalsystems/neat-contract/blob/master/package.json#L51 but doesn't appear in `dependencies`.

With Thane's help, I was able to get a global install with `npm i && npm i -g`.

**Comment by thanethomson** [comment]
In the meantime we can work around this bug by using the Docker image.

**Comment by shonfeder** [comment]
Irrelevant after rewrite in go.
