### ISSUE TITLE
Clean up install script

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/themis-contract#35]
Somewhat related to https://github.com/informalsystems/themis-contract/issues/2

I found the script a bit weird, and ended up copying and pasting what I needed.

For instance, it installs `git`. I think it's safe to assume the user already has git. 

It also seems to assume the user doesn't have the local repo. I think we can expect folks to clone the repo and build from within the repo. This should simplify all the `/tmp` stuff.

Folks likely already have some version of node, and maybe don't want to use brew for it. 

I think it would be best to include instructions for installation directly in the readme, consisting of a very small set of commands necessary to install the binary, assuming the dependencies are already installed and we're inside the repo.

Oh, we should also mention that we expect `$EDITOR` to be set.

**Comment by ebuchman** [comment]
:doh: it occurs to me now that what I was looking for was directly below, under `Other Systems`. This was a bit misleading :)

**Comment by zramsay** [comment]
looks like this was for the old version. now we have brew and and working makefile
