### ISSUE TITLE
CLI Command Organization

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/themis-contract#38]
We currently have a lot of high level commands.

I suspect we can get a better UX with some more hierarchical structure. eg. `themis-contract id add` and `themis-contract id list` instead of `save-identity` and `list-identity`. See the `gaiacli` tool for instance.

Also there's probably a better way to structure the id/counterparty/signatory distinctions, but I don't exactly know yet.

**Comment by thanethomson** [comment]
With v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`) being built in Go and using Cobra for its CLI organization, this has been restructured now in a more reasonable way.
