### ISSUE TITLE
Fetching templates

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/themis-contract#40]
It should be possible to specify a template URL on `new` to fetch the template from the web. This will facilitate using a common set of templates stored in a canonical location, rather than having to copy them around.

We should also probably create an index of templates in a local profile so we can refer to them by name, ie. `--template-id employee` could look up `employee` in a local config file to find the URL where to pull from. 

Wasn't clear if/how this relates to #6

**Comment by shonfeder** [comment]
This is closely related to the `review` command suggested in #8. #8 probably need to be factored out, perhaps merging with this, or splitting `review` into a higher level command that's based on this functionality.

**Comment by ebuchman** [comment]
As a first order approach to simplify this we can assume the template dir already exists locally and its location can be kept in some global config file. 

Then we don't even need to fetch from the internet we can just copy it out of the local repo.

If fetching from the internet is simple enough than no biggie, just trying to find acceptable ways to simplify up front ...

**Comment by thanethomson** [comment]
Now implemented in v0.2, as described in #60 (currently on branch `prototype/v2`, soon to be merged to `master`).
