### ISSUE TITLE
Porcelain to generate, compile, sign

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/themis-contract#41]
Currently, generating, compiling, and signing are three different steps. While this is great for low level plumbing, ultimately this should be possible by a single command.

This will be critical to demonstrate the value of the tool in more rapidly firing off contracts.

**Comment by shonfeder** [comment]
I think this is a duplicate of #8, specifically the `execute` command proposed there.

**Comment by ebuchman** [comment]
Yep!
