### ISSUE TITLE
Counterparty environment

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/themis-contract#43]
Once counterparties are added to your profile, it should be possible to set them in the environment, like you can activate a python virtualenv.

Then you don't need to worry about specifying who you are in the contract and what your signatory is, it's already there in the environment and can be populated in the params file by default.

This will dramatically improve the UX by reducing the need to type out redundant information. Most people will have only one company/signatory to set and activate and all contracts will come from them. For others there may be multiple, but it should be easy to switch between them - easier than typing in who you are into the params file or as a flag in one of the commands.

Eg. `themis-contract workas informal-systems ebuchman` ... probably needs some work but something  like that ... then all contracts will have informal-systems as a counterparty with ebuchman as a signatory

**Comment by thanethomson** [comment]
Now implemented in v0.2, as discussed on #60 (currently on branch `prototype/v2`, soon to be merged to `master`).
