### ISSUE TITLE
Clarify and enhance data model of counterparties and signatories

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/themis-contract#45]
At present, our data model is as follows:

![arch--2020-05-22](https://user-images.githubusercontent.com/212999/82818151-46d14d80-9e6c-11ea-9d6b-cb502352038e.png)

In this model we have **contracts**, which have two or more **counterparties**. Counterparties are currently always treated as collectives with one or more **signatories**. An **identity** is effectively a special case of a signatory, and allows a user to sign a contract as that particular signatory.

There are two issues with this approach:

1. Always treating a counterparty as a collective can be rather tedious and can result in redundant information needing to be added for both. This turns out to be quite a common occurrence, since a large number of contracts take place between a company (collective) and an individual.
2. Our current notion of "identities" is confusing with signatories. A better concept here might be to have "profiles" for users of Themis Contract.

From these two suggestions, our model can be altered to resemble the following:

![prototypev2-arch--2020-05-25](https://user-images.githubusercontent.com/212999/82824180-dda30780-9e76-11ea-93ad-5c609b3212d0.png)

In this new model, a **contract** has two or more **counterparties** (as in the old model). Here, however, a "counterparty" is an abstract base entity (doesn't actually exist), but is realized through either a **signatory** (a single signer) or a **collective counterparty** (e.g. a company with one or more signatories).

A **profile** is used to store information locally on a user's machine about that user. Users can have multiple profiles because sometimes they may have to sign on behalf of different entities.

**Comment by shonfeder** [comment]
Is this the correct type for what you're proposing?

```rust
enum Counterparty {
    Collective(Set<Signatory>),
    Singular(Signatory)
}
```

**Comment by thanethomson** [comment]
> Is this the correct type for what you're proposing?

Sure, that's how you'd implement it in Rust 👍

**Comment by shonfeder** [comment]
I just picked rust syntax thinking it would be most perspicuous in this context, but guess I should have used TypeScript. The type reflecting this structure should be same, regardless of the syntax.

**Comment by thanethomson** [comment]
We are no longer going to implement this model in v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`).

We're now requiring that contracts expose a `signatories` array that, at a minimum, is of the following (Dhall) type:

```dhall
let Signatory : Type =
  { id : Text
  , name : Text
  , email : Text
  }

let signatories : List Signatory =
  [ { id = "signatory1"
    , name = "Harry Henderson"
    , email = "harry@henderson.com"
    }
  ]

in { signatories = signatories }
```

You can add any additional arbitrary fields to the signatory type (these will be passed through to your contract when rendering), but any notion of counterparties/organizations/etc. is totally up to you to define in your own contract. This is the only way we're going to get flexibility, while also providing Themis Contract with the minimum amount of information it needs to facilitate its signing mechanics.
