### ISSUE TITLE
Parameter extraction from tempates is error prone  

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#53]
The `new` command extracts parameters from out of a contract template and makes a config file for these params.

The immediate shortcomings in the current parameter extraction are:

- Objects are sometimes not identified correctly, so `new` sets the parameter with an empty string in the config instead of the proper object.
- There is no way to include any context or documentation to help inform users what the parameters are for.

This might not really be doable in a satisfactorily way for mustache, due to issues like https://github.com/janl/mustache.js/issues/538#issuecomment-169008780

This was discussed during our walk through of the tool last week.
 
Related to #48 and  #42

**Comment by thanethomson** [comment]
No longer a problem, given how we've implemented the contract structure in v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`).
