### ISSUE TITLE
Add procelain to manage cloning, and committing to repos

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#6]
Currently users have to:

1. clone a contract repo
2. cd into the repo
3. compile and sign
4. stage changes
5. commit changes
6. push back to repo

It would provide a cleaner UI if we wrap (1) - (2) and (5) - (6) in some porcelain. We could download the repositories into the `~/.neat` directory and make the list of signed contracts available. Registering a repo could just be a matter of pasting the giturl.

**Comment by shonfeder** [comment]
Labeled as high priority, based on its direct relevance for this need from the one-pager alignment doc:

> Ability for both technical and non-technical counterparties to sign their contract using the tool or an external integration.

on the grounds that having to be a competent git user shouldn't be a prerequisite for compiling the contract and making changes.

**Comment by thanethomson** [comment]
Now available in v0.2 (currently on branch `prototype/v2`, soon to be merged to `master`).
