### ISSUE TITLE
General project context/history questions

### ISSUE THREAD

**Issue by patcon** [informalsystems/themis-contract#96]
Hi there -- sorry if the issue queue is the wrong place for this:

1. Any synchronous chat space?
2. Is this repo in any way related to the prior Themis project that was exploring digital corporate constitutions, related to the defunct One-Click Org project?
    - https://circus-foundation.org/current-projects/themis-designing-emergent-democracy/
    - http://web.archive.org/web/20110413163732/http://www.oneclickorgs.com/2010/08/19/joi-ito-joins-one-click-orgs-advisory-board/

Thanks!

**Comment by shonfeder** [comment]
Thanks for the question!

This repo is not related! `themis`, being a lovely name, has been used by many more and less closely related projects (perhaps too may -- we are considering a name change ;) ).

I created a stream in our companies public Zulip instance, which you are welcome to join for synchronous chat. Fair warning that you'll be the second member :) https://informal-systems.zulipchat.com/#narrow/stream/268309-disco-tools

Some context/history is available in Informal Systems blog posts:

- On our org's general missions and vision (and hints at how this effort is related): https://informal.systems/2020/02/24/introducing-informal/
- Development and motive is detailed as part ofour technical progress updates from the last year:
  - https://informal.systems/2020/05/07/q1-tech-update/
  - https://informal.systems/2020/07/31/q2-tech-update/
- On choice of Dhall for the principle configuration format is explained here: https://informal.systems/2020/10/28/configuration-file-formats/

Any other questions on this front very welcome here :)

**Comment by patcon** [comment]
Thanks for the invite! Was making my way through the blog posts in advance of the event tomorrow, anyhow :)

(I'm a member of @hyphacoop who should be jumping on a call with y'all in January fyi)

Would it be helpful if I created a PR to add the Zulip reference to a section of the README? Also, if there's a canonical repo somewhere in the org, it could go there. no pressure if you'd just like it to stay here though

(A few orgs I've participated in keep an `foo/overview` repo for general stuff -- licensing, comms, 10,000ft context, etc: https://github.com/edgi-govdata-archiving or https://github.com/civictechto/)

**Comment by shonfeder** [comment]
Oh nice! I am hoping to attend your virtual holiday internet thingy on Sunday.

Thanks for the suggestion for an overview repo. I'll report that back internally.

PRs are welcome, tho I'll be sure to add the Zulip link to the readme once I sync up internally.

**Comment by patcon** [comment]
Close in light of https://github.com/informalsystems/themis-contract/pull/110
